# Generated by Django 6.1.1 on 2026-09-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('product', 'name')},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='key',
        ),
    ]
