# Generated by Django 6.1.1 on 2026-09-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_petcategory_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='shop.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='reference_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='collection_products', to='shop.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
