# Generated by Django 6.1.1 on 2026-09-06 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_exact_selling_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_cart',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
