# Generated by Django 6.1.1 on 2026-09-06 22:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_crm_stock_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crmactivity',
            options={'ordering': ['-created_at', '-pk'], 'permissions': [('access_crm', 'Access customer and order CRM'), ('manage_crm_orders', 'Process and cancel orders in CRM'), ('adjust_crm_inventory', 'Adjust stock through audited CRM workflow'), ('write_crm_notes', 'Write internal CRM notes'), ('manage_crm_coupons', 'Create and edit checkout coupons')]},
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='crmactivity',
            name='kind',
            field=models.CharField(choices=[('note', 'Internal note'), ('status', 'Order status'), ('coupon', 'Coupon change')], max_length=20),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9][A-Z0-9_-]{2,39}$', 'Use 3–40 letters, numbers, hyphens or underscores.')])),
                ('name', models.CharField(help_text='Internal campaign name.', max_length=120)),
                ('kind', models.CharField(choices=[('percent', 'Percentage off'), ('fixed', 'Fixed amount off (₹)')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('minimum_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('used_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='coupon_positive_value'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'percent'), _negated=True), ('value__lte', 100), _connector='OR'), name='coupon_percent_maximum'), models.CheckConstraint(condition=models.Q(('minimum_subtotal__gte', 0)), name='coupon_nonnegative_minimum')],
            },
        ),
        migrations.AddField(
            model_name='crmactivity',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity', to='shop.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.coupon'),
        ),
    ]
