# Generated by Django 6.1.1 on 2026-09-07 19:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_media_nutrition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['display_order', 'name', 'pk']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Other exact options, such as flavour or colour.'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='comparison_group',
            field=models.CharField(blank=True, help_text='Only identical formulations/items may share a comparison group. Blank disables value comparisons.', max_length=100),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_variants', to='shop.productimage'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Verified net pack quantity, not animal weight or shipping weight.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('L', 'L'), ('count', 'count')], max_length=10),
        ),
    ]
