# Generated by Django 6.1.1 on 2026-09-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_variant_buying'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_family',
            field=models.ForeignKey(blank=True, help_text='Canonical listing for verified sibling packs. Existing stock and orders stay on this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='shop.product'),
        ),
    ]
