# Generated by Django 6.1.1 on 2026-09-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_seed_existing_order_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.PositiveBigIntegerField(help_text='Server-calculated INR paise')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('state', models.CharField(choices=[('new', 'Not started'), ('creating', 'Creating'), ('ready', 'Ready'), ('uncertain', 'Needs reconciliation'), ('paid', 'Verified paid')], default='new', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='ordernotification',
            name='one_notification_per_order_event_channel',
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='audience',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('pending', 'Placed'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ordernotification',
            constraint=models.UniqueConstraint(fields=('event', 'channel', 'audience'), name='one_notification_per_event_audience'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempt', to='shop.order'),
        ),
    ]
