# Generated by Django 6.1.1 on 2026-09-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_purchase_flow_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordernotification',
            name='retryable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordernotification',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Provider accepted'), ('failed', 'Failed'), ('preview', 'Sandbox preview only')], default='pending', max_length=12),
        ),
    ]
