# Generated by Django 6.1.1 on 2026-09-25 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_brevo_outbox_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('approve_catalog', 'Can approve catalog products for sale')]},
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_approved_digest',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.CreateModel(
            name='CatalogReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('held', 'Held for review')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('evidence', models.TextField()),
                ('snapshot', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_reviews', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
