# Generated by Django 6.1.1 on 2026-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_catalog_review_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='merchandising_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Explicit manual homepage selection; imported flags alone never publish.'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchandising_rank',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
