# Generated by Django 6.1.1 on 2026-10-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_public_launch_foundations'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='family_reference_for',
            field=models.ForeignKey(blank=True, help_text='Staff-approved generic reference for this canonical family, never an exact-pack assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_family_artwork', to='shop.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='family_reference_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
