# Generated by Django 6.1.1 on 2026-10-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_trusted_family_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
