# Generated by Django 6.1.1 on 2026-10-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productimage_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotification',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
