"""
Django settings for suryavets project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

try:
    import dj_database_url
except ImportError:  # Lets a local developer run SQLite before installing production extras.
    dj_database_url = None

try:
    import whitenoise  # noqa: F401
    HAS_WHITENOISE = True
except ImportError:
    HAS_WHITENOISE = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


IS_RENDER = bool(os.environ.get('RENDER') or os.environ.get('RENDER_EXTERNAL_URL'))
DEBUG = env_bool('DEBUG', default=not IS_RENDER)
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG=False.')
    SECRET_KEY = 'django-insecure-local-development-only-change-before-production'

default_hosts = '127.0.0.1,localhost' if DEBUG else os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', default_hosts).split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
if IS_RENDER and os.environ.get('RENDER_EXTERNAL_URL'):
    CSRF_TRUSTED_ORIGINS.append(os.environ['RENDER_EXTERNAL_URL'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'shop.seo.IndexingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if HAS_WHITENOISE:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'suryavets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'shop' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'shop.context_processors.cart_count',
                'shop.context_processors.get_categories',
                'shop.context_processors.get_banners',
                'shop.context_processors.get_featured_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'suryavets.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    if dj_database_url is None:
        raise ImproperlyConfigured('Install dj-database-url before using DATABASE_URL.')
    DATABASES = {'default': dj_database_url.config(conn_max_age=600, conn_health_checks=True)}
else:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = []  # AppDirectoriesFinder already discovers shop/static.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG else 'whitenoise.storage.CompressedStaticFilesStorage'
        ),
    },
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
}

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': os.environ.get(
            'DJANGO_EMAIL_BACKEND',
            'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
        ),
    },
}

LOGIN_URL = 'shop:login'
ORDER_EMAIL_ENABLED = env_bool('ORDER_EMAIL_ENABLED', default=False)
ORDER_EMAIL_AUTO_SEND = env_bool('ORDER_EMAIL_AUTO_SEND', default=True)
ORDER_NOTIFICATION_EMAIL = os.environ.get('ORDER_NOTIFICATION_EMAIL', '')
PUBLIC_SITE_URL = os.environ.get('PUBLIC_SITE_URL', '').rstrip('/')
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME') or 'SuryaVets'
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '')
# Selecting the Brevo backend alone cannot send real email; live sending is explicit.
BREVO_SANDBOX = env_bool('BREVO_SANDBOX', default=True) if os.environ.get('BREVO_SANDBOX') else True
BREVO_TIMEOUT = max(1, min(30, int(os.environ.get('BREVO_TIMEOUT') or 15)))
ORDER_EMAIL_MAX_ATTEMPTS = 5
if MAILERS['default']['BACKEND'] == 'django.core.mail.backends.smtp.EmailBackend':
    MAILERS['default']['OPTIONS'] = {'host': os.environ.get('EMAIL_HOST', ''), 'port': int(os.environ.get('EMAIL_PORT') or 587),
        'username': os.environ.get('EMAIL_HOST_USER', ''), 'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
        'use_tls': env_bool('EMAIL_USE_TLS', default=True), 'timeout': 15}
# Deliberately test-only. Live credentials are rejected by the payment service.
RAZORPAY_ENABLED = env_bool('RAZORPAY_ENABLED', default=False)
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Surya Vets <noreply@localhost>')
LOGIN_REDIRECT_URL = 'shop:profile'
HOMEPAGE_MERCHANDISING_LIMIT = 12  # Manual picks per main section, clamped to 1–20.
LOGOUT_REDIRECT_URL = 'shop:index'
SITE_NOINDEX = env_bool('SITE_NOINDEX', default=True)
ANALYTICS_EVENTS_ENABLED = env_bool('ANALYTICS_EVENTS_ENABLED', default=False)
PASSWORD_RESET_EMAIL_ENABLED = env_bool('PASSWORD_RESET_EMAIL_ENABLED', default=False)
PASSWORD_RESET_TIMEOUT = 3600
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
X_FRAME_OPTIONS = 'DENY'
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
MEDIA_STORAGE_BACKEND = os.environ.get('MEDIA_STORAGE_BACKEND', 'django.core.files.storage.FileSystemStorage')
STORAGES['default']['BACKEND'] = MEDIA_STORAGE_BACKEND
if MEDIA_STORAGE_BACKEND == 'storages.backends.s3.S3Storage':
    STORAGES['default']['OPTIONS'] = {
        'bucket_name': os.environ.get('AWS_STORAGE_BUCKET_NAME', ''),
        'region_name': os.environ.get('AWS_S3_REGION_NAME') or None,
        'endpoint_url': os.environ.get('AWS_S3_ENDPOINT_URL') or None,
        'file_overwrite': False,
    }
    if not DEBUG and not STORAGES['default']['OPTIONS']['bucket_name']:
        raise ImproperlyConfigured('Set AWS_STORAGE_BUCKET_NAME for external media.')
if not DEBUG:
    if not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS:
        raise ImproperlyConfigured('Set explicit DJANGO_ALLOWED_HOSTS for production.')
    if len(SECRET_KEY) < 50 or SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('Use a strong production DJANGO_SECRET_KEY.')
    if not DATABASE_URL or DATABASES['default']['ENGINE'] != 'django.db.backends.postgresql':
        raise ImproperlyConfigured('Production requires a PostgreSQL DATABASE_URL.')
    if not HAS_WHITENOISE:
        raise ImproperlyConfigured('Install WhiteNoise for production static assets.')
    from urllib.parse import urlsplit
    public_origin = urlsplit(PUBLIC_SITE_URL)
    if public_origin.scheme != 'https' or not public_origin.netloc or public_origin.path or public_origin.query or public_origin.fragment or public_origin.username:
        raise ImproperlyConfigured('PUBLIC_SITE_URL must be an HTTPS origin, without a path.')
    if MEDIA_STORAGE_BACKEND == 'django.core.files.storage.FileSystemStorage' and not os.environ.get('PERSISTENT_MEDIA_ROOT'):
        raise ImproperlyConfigured('Configure persistent/external media before production.')
if os.environ.get('PERSISTENT_MEDIA_ROOT'):
    MEDIA_ROOT = Path(os.environ['PERSISTENT_MEDIA_ROOT'])

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
